package com.guyteichman.mageknightbuddy.data

import com.guyteichman.mageknightbuddy.domain.Knight
import com.guyteichman.mageknightbuddy.domain.Outcome
import com.guyteichman.mageknightbuddy.domain.Scenario
import com.guyteichman.mageknightbuddy.domain.ScoringSession
import java.time.Instant
import kotlinx.serialization.Serializable

/**
 * The top-level shape of an exported backup file (see [BackupCodec] and ADR-0009). This is a
 * separate representation from [ScoringSessionEntity] on purpose: the DB schema and the on-disk
 * backup format evolve independently, so neither is dragged along when the other changes.
 *
 * [formatVersion] lets a future build detect and reject a backup written by a newer format it
 * doesn't understand (rather than silently mis-parsing it - see [BackupCodec.decode]);
 * [exportedAtEpochMillis] records when the snapshot was taken (informational, for the restore UI).
 */
@Serializable
data class BackupDocument(
    val formatVersion: Int,
    val exportedAtEpochMillis: Long,
    val records: List<BackupRecordDto>,
)

/**
 * One scoring session inside a [BackupDocument]. Mirrors [ScoringSessionEntity]'s columns but keeps
 * [input] as a *structured* [ScoringInputDto] (not the entity's escaped JSON string) so the backup
 * file stays human-readable, and deliberately omits the DB's autogenerated `id`: it's device-local
 * and meaningless across installs, so restore lets SQLite assign fresh ids instead.
 */
@Serializable
data class BackupRecordDto(
    val scenario: String,
    val knight: String,
    val playerName: String?,
    val input: ScoringInputDto,
    val score: Int,
    val outcome: String,
    val playedAtEpochMillis: Long,
)

/** Converts a domain [ScoringSession] into its backup-file record, encoding [input] structurally. */
fun ScoringSession.toBackupRecord(): BackupRecordDto = BackupRecordDto(
    scenario = scenario.id,
    knight = knight.name,
    playerName = playerName,
    // toDto() (see ScoringInputMapper) is the same domain -> ScoringInputDto conversion the Room
    // mapper uses; here the result is nested as structured JSON rather than encoded to a string.
    input = input.toDto(),
    score = score,
    outcome = outcome.name,
    playedAtEpochMillis = playedAt.toEpochMilli(),
)

/**
 * Converts a backup record back into a domain [ScoringSession]. Throws if [scenario]/[knight]/
 * [outcome] name a value this build doesn't know (NoSuchElementException from [Scenario.fromId],
 * IllegalArgumentException from the enum `valueOf`s) - [BackupCodec.decode] catches both and reports
 * the whole file as malformed rather than letting it propagate.
 */
fun BackupRecordDto.toDomain(): ScoringSession = ScoringSession(
    scenario = Scenario.fromId(scenario),
    knight = Knight.valueOf(knight),
    playerName = playerName,
    input = input.toDomain(),
    score = score,
    outcome = Outcome.valueOf(outcome),
    playedAt = Instant.ofEpochMilli(playedAtEpochMillis),
)
