package com.guyteichman.mageknightbuddy.data

import com.guyteichman.mageknightbuddy.domain.ScoringSession
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

/**
 * The persistence-facing entry point the rest of the app uses to save and load
 * [ScoringSession]s, hiding the Room [ScoringSessionDao] and the entity<->domain conversion
 * behind a domain-typed API. This is the only place outside ScoringSessionMapper.kt that should
 * need to know [ScoringSessionEntity] exists.
 */
class ScoringSessionRepository(private val dao: ScoringSessionDao) {
    // toEntity() (see ScoringSessionMapper.kt) does the domain -> Room conversion before handing
    // off to the DAO's generated insert.
    suspend fun save(session: ScoringSession) {
        dao.insert(session.toEntity())
    }

    // Flow.map here transforms each emitted List<ScoringSessionEntity> into a
    // List<StoredScoringSession> via toStored(), without subscribing/collecting the flow itself -
    // callers still get a live, auto-updating stream. Each item carries its Room id (unlike the pure
    // domain ScoringSession), so the Scoreboard can delete an individual game by id (issue #304).
    fun getAll(): Flow<List<StoredScoringSession>> =
        dao.getAll().map { entities -> entities.map { it.toStored() } }

    /** Deletes the single saved game with this Room [id] (see [StoredScoringSession.id]); a no-op if it's already gone. */
    suspend fun delete(id: Long) = dao.deleteById(id)

    // One-shot snapshot of the whole history, for writing a backup file (see BackupCodec).
    suspend fun exportAll(): List<ScoringSession> =
        dao.getAllOnce().map { it.toDomain() }

    /**
     * Replaces the entire saved history with [sessions] - the "restore from backup" operation.
     * Atomic (see [ScoringSessionDao.replaceAll]); any prior records are discarded, and each
     * restored row gets a fresh autogenerated id (the backup carries none - see [BackupRecordDto]).
     */
    suspend fun replaceAll(sessions: List<ScoringSession>) =
        dao.replaceAll(sessions.map { it.toEntity() })
}
