package com.guyteichman.mageknightbuddy.data

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.guyteichman.mageknightbuddy.domain.Knight
import com.guyteichman.mageknightbuddy.domain.Outcome
import com.guyteichman.mageknightbuddy.domain.Scenario
import com.guyteichman.mageknightbuddy.domain.ScoringSession
import com.guyteichman.mageknightbuddy.domain.SoloConquestScoringInput
import com.guyteichman.mageknightbuddy.domain.StandardAchievements
import com.guyteichman.mageknightbuddy.domain.UnitTally
import java.io.File
import java.time.Instant
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest

class ScoringSessionRepositoryTest {
    private lateinit var database: MageKnightBuddyDatabase
    private lateinit var dbFile: File
    private lateinit var repository: ScoringSessionRepository

    @BeforeTest
    fun setUp() {
        dbFile = File.createTempFile("test-repository", ".db")
        database = Room.databaseBuilder<MageKnightBuddyDatabase>(name = dbFile.absolutePath)
            .setDriver(BundledSQLiteDriver())
            .build()
        repository = ScoringSessionRepository(database.scoringSessionDao())
    }

    @AfterTest
    fun tearDown() {
        database.close()
        dbFile.delete()
    }

    @Test
    fun `save then getAll round-trips a ScoringSession through Room`() = runTest {
        val session = ScoringSession.create(
            scenario = Scenario.SoloConquest,
            knight = Knight.GOLDYX,
            playerName = "Guy",
            input = SoloConquestScoringInput(
                fame = 42,
                standardAchievements = StandardAchievements(
                    spellsInDeck = 1,
                    advancedActionsInDeck = 1,
                    units = (1..4).map { level -> UnitTally(level = level, healthyCount = 0, woundedCount = 0) },
                    shieldsOnAdventureSites = 0,
                    artifacts = 0,
                    crystalsInInventory = 0,
                    shieldsOnConquerSites = 0,
                    woundsInDeck = 0,
                ),
                citiesConquered = 1,
                roundsFinishedEarly = 0,
                cardsRemainingInDummyDeck = 0,
                endOfRoundAnnounced = true,
                questPoints = 0,
            ),
            playedAt = Instant.parse("2026-07-18T10:00:00Z"),
        )

        repository.save(session)

        val result = repository.getAll().first()

        assertEquals(1, result.size)
        // getAll now yields StoredScoringSession (id + session), so the domain object lives under .session.
        assertEquals(session, result.single().session)
        assertEquals(Outcome.LOST, result.single().session.outcome)
    }

    @Test
    fun `getAll exposes each row's autogenerated id`() = runTest {
        repository.save(session(knight = Knight.TOVAK, playedAt = Instant.parse("2026-07-10T00:00:00Z")))
        repository.save(session(knight = Knight.GOLDYX, playedAt = Instant.parse("2026-07-11T00:00:00Z")))

        val ids = repository.getAll().first().map { it.id }

        // Two distinct, real (non-placeholder) ids surface - the handle the Scoreboard deletes by.
        assertEquals(2, ids.size)
        assertEquals(2, ids.toSet().size)
        assertTrue(ids.all { it != 0L })
    }

    @Test
    fun `delete removes only the game with the given id`() = runTest {
        // Two saved games, built the normal way; GOLDYX is the newer one (sorts first in getAll).
        repository.save(session(knight = Knight.TOVAK, playedAt = Instant.parse("2026-07-10T00:00:00Z")))
        repository.save(session(knight = Knight.GOLDYX, playedAt = Instant.parse("2026-07-11T00:00:00Z")))
        val goldyxId = repository.getAll().first().single { it.session.knight == Knight.GOLDYX }.id

        repository.delete(goldyxId)

        // Exactly the targeted game is gone; the other is untouched.
        val remaining = repository.getAll().first()
        assertEquals(listOf(Knight.TOVAK), remaining.map { it.session.knight })
    }

    @Test
    fun `exportAll returns a snapshot of every saved session, newest first`() = runTest {
        // Build the starting state through the repository's own save(), not by hand-inserting rows.
        val older = session(knight = Knight.TOVAK, playedAt = Instant.parse("2026-07-10T00:00:00Z"))
        val newer = session(knight = Knight.GOLDYX, playedAt = Instant.parse("2026-07-20T00:00:00Z"))
        repository.save(older)
        repository.save(newer)

        val exported = repository.exportAll()

        assertEquals(listOf(newer, older), exported)
    }

    @Test
    fun `replaceAll discards existing records and installs exactly the given set`() = runTest {
        // Two pre-existing records, saved the normal way.
        repository.save(session(knight = Knight.TOVAK, playedAt = Instant.parse("2026-07-10T00:00:00Z")))
        repository.save(session(knight = Knight.GOLDYX, playedAt = Instant.parse("2026-07-11T00:00:00Z")))

        // Restore a completely different single-record backup over them.
        val restored = session(knight = Knight.ARYTHEA, playedAt = Instant.parse("2026-07-25T00:00:00Z"))
        repository.replaceAll(listOf(restored))

        // Both live (getAll) and snapshot (exportAll) reads reflect only the restored set - the two
        // originals are gone, not merged. getAll yields StoredScoringSession, so compare on .session.
        assertEquals(listOf(restored), repository.getAll().first().map { it.session })
        assertEquals(listOf(restored), repository.exportAll())
    }

    @Test
    fun `replaceAll with an empty list clears the whole history`() = runTest {
        repository.save(session(knight = Knight.TOVAK, playedAt = Instant.parse("2026-07-10T00:00:00Z")))

        repository.replaceAll(emptyList())

        assertEquals(emptyList(), repository.exportAll())
    }

    // Minimal Solo Conquest session builder, varying only the fields the tests above distinguish on.
    private fun session(knight: Knight, playedAt: Instant) = ScoringSession.create(
        scenario = Scenario.SoloConquest,
        knight = knight,
        playerName = null,
        input = SoloConquestScoringInput(
            fame = 10,
            standardAchievements = StandardAchievements(
                spellsInDeck = 0,
                advancedActionsInDeck = 0,
                units = (1..4).map { level -> UnitTally(level = level, healthyCount = 0, woundedCount = 0) },
                shieldsOnAdventureSites = 0,
                artifacts = 0,
                crystalsInInventory = 0,
                shieldsOnConquerSites = 0,
                woundsInDeck = 0,
            ),
            citiesConquered = 0,
            roundsFinishedEarly = 0,
            cardsRemainingInDummyDeck = 0,
            endOfRoundAnnounced = true,
            questPoints = 0,
        ),
        playedAt = playedAt,
    )
}
